addSbtPlugin("org.scalameta"             % "sbt-scalafmt"              % "2.4.2")
addSbtPlugin("com.github.cb372"          % "sbt-explicit-dependencies" % "0.2.13")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"              % "0.1.10")
addSbtPlugin("com.jsuereth"              % "sbt-pgp"                   % "2.0.1")
addSbtPlugin("com.github.gseitz"         % "sbt-release"               % "1.0.10")
